version: '3.1'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'mystery_shopping'
      MYSQL_USER: 'mysteryUser'
      MYSQL_PASSWORD: 'pass-mystery'
      MYSQL_ROOT_PASSWORD: 'pass-root'
    ports:
      - 3306:3306
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:
